import { useState, useEffect, useRef } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import { Clock, Play, Square, FileText, MapPin, AlertTriangle, CheckCircle } from 'lucide-react'
import toast from 'react-hot-toast'
import './DetentionTimer.css'

function formatTime(seconds) {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = seconds % 60
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

function formatDuration(minutes) {
  if (minutes < 60) return `${minutes} min`
  const h = Math.floor(minutes / 60)
  const m = minutes % 60
  return m > 0 ? `${h}h ${m}m` : `${h}h`
}

export default function DetentionTimer() {
  const { user } = useAuth()
  const [running, setRunning] = useState(false)
  const [elapsed, setElapsed] = useState(0)
  const [arrivedAt, setArrivedAt] = useState(null)
  const [departedAt, setDepartedAt] = useState(null)
  const [freeTimeMinutes, setFreeTimeMinutes] = useState(120)
  const [facilityName, setFacilityName] = useState('')
  const [facilityAddress, setFacilityAddress] = useState('')
  const [brokerName, setBrokerName] = useState('')
  const [loadNumber, setLoadNumber] = useState('')
  const [notes, setNotes] = useState('')
  const [saved, setSaved] = useState(false)
  const [pastLogs, setPastLogs] = useState([])
  const intervalRef = useRef(null)
  const startTimeRef = useRef(null)

  useEffect(() => {
    if (user) fetchPastLogs()
  }, [user])

  useEffect(() => {
    return () => clearInterval(intervalRef.current)
  }, [])

  const fetchPastLogs = async () => {
    const { data } = await supabase
      .from('detention_logs')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(10)
    setPastLogs(data || [])
  }

  const handleStart = () => {
    if (!facilityName.trim()) {
      toast.error('Enter the facility name first')
      return
    }
    const now = new Date()
    setArrivedAt(now)
    setDepartedAt(null)
    setElapsed(0)
    setSaved(false)
    startTimeRef.current = now
    setRunning(true)
    intervalRef.current = setInterval(() => {
      setElapsed(prev => prev + 1)
    }, 1000)
    toast.success('Timer started — clock is running')
  }

  const handleStop = () => {
    clearInterval(intervalRef.current)
    setRunning(false)
    setDepartedAt(new Date())
  }

  const detentionSeconds = Math.max(0, elapsed - freeTimeMinutes * 60)
  const detentionMinutes = Math.floor(detentionSeconds / 60)
  const isInDetention = elapsed > freeTimeMinutes * 60
  const freeTimeRemaining = Math.max(0, freeTimeMinutes * 60 - elapsed)
  const freeTimePercent = Math.min(100, (elapsed / (freeTimeMinutes * 60)) * 100)

  const handleSaveLog = async () => {
    if (!user) { toast.error('Sign in to save logs'); return }
    if (!arrivedAt || !departedAt) { toast.error('Stop the timer first'); return }

    try {
      const { error } = await supabase.from('detention_logs').insert({
        user_id: user.id,
        facility_name: facilityName,
        facility_address: facilityAddress || null,
        arrived_at: arrivedAt.toISOString(),
        departed_at: departedAt.toISOString(),
        free_time_minutes: freeTimeMinutes,
        detention_minutes: detentionMinutes,
        notes: notes || null,
        broker_name: brokerName || null,
        load_number: loadNumber || null
      })
      if (error) throw error
      setSaved(true)
      toast.success('Log saved!')
      fetchPastLogs()
    } catch (err) {
      toast.error('Failed to save log')
    }
  }

  const generateReport = () => {
    if (!arrivedAt) return

    const report = `
DETENTION REPORT — DOCKWARRIOR
================================
Date: ${(arrivedAt).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

FACILITY: ${facilityName.toUpperCase()}
${facilityAddress ? `Address: ${facilityAddress}` : ''}
${brokerName ? `Broker: ${brokerName}` : ''}
${loadNumber ? `Load #: ${loadNumber}` : ''}

TIMELINE
--------
Arrived:   ${arrivedAt.toLocaleTimeString()}
Departed:  ${departedAt ? departedAt.toLocaleTimeString() : 'Still on site'}
Free Time: ${freeTimeMinutes} minutes
Total Time: ${formatDuration(Math.floor(elapsed / 60))}

DETENTION
---------
Detention Time: ${detentionMinutes > 0 ? formatDuration(detentionMinutes) : 'None — within free time'}
${detentionMinutes > 0 ? `⚠ DETENTION OCCURRED — ${detentionMinutes} minutes beyond free time` : '✓ No detention'}

${notes ? `NOTES\n-----\n${notes}` : ''}

Generated by DockWarrior — dockwarrior.com
================================
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `detention-report-${facilityName.replace(/\s+/g, '-').toLowerCase()}-${arrivedAt.toISOString().slice(0,10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Report downloaded!')
  }

  const handleReset = () => {
    clearInterval(intervalRef.current)
    setRunning(false)
    setElapsed(0)
    setArrivedAt(null)
    setDepartedAt(null)
    setSaved(false)
  }

  return (
    <div className="page">
      <div className="section-header">
        <div className="accent-line" />
        <h2>Detention Timer</h2>
        <p>Start the clock when you arrive. Build your paper trail automatically.</p>
      </div>

      <div className="timer-layout">
        {/* MAIN TIMER */}
        <div className="timer-main">
          {/* FACILITY INFO */}
          <div className="card timer-setup">
            <h3 className="setup-title">Facility Info</h3>
            <div className="form-group">
              <label className="form-label">Facility Name *</label>
              <input
                className="form-input"
                placeholder="e.g. Amazon MDW2 Joliet"
                value={facilityName}
                onChange={e => setFacilityName(e.target.value)}
                disabled={running}
              />
            </div>
            <div className="grid-2">
              <div className="form-group">
                <label className="form-label">Address (optional)</label>
                <input
                  className="form-input"
                  placeholder="Street address"
                  value={facilityAddress}
                  onChange={e => setFacilityAddress(e.target.value)}
                  disabled={running}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Free Time (minutes)</label>
                <select
                  className="form-input"
                  value={freeTimeMinutes}
                  onChange={e => setFreeTimeMinutes(parseInt(e.target.value))}
                  disabled={running}
                >
                  <option value={60}>60 min (1 hour)</option>
                  <option value={90}>90 min</option>
                  <option value={120}>120 min (standard)</option>
                  <option value={180}>180 min (3 hours)</option>
                  <option value={240}>240 min (4 hours)</option>
                </select>
              </div>
            </div>
            <div className="grid-2">
              <div className="form-group">
                <label className="form-label">Broker Name</label>
                <input
                  className="form-input"
                  placeholder="Broker company"
                  value={brokerName}
                  onChange={e => setBrokerName(e.target.value)}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Load Number</label>
                <input
                  className="form-input"
                  placeholder="Reference #"
                  value={loadNumber}
                  onChange={e => setLoadNumber(e.target.value)}
                />
              </div>
            </div>
          </div>

          {/* CLOCK DISPLAY */}
          <div className={`card timer-clock ${isInDetention ? 'in-detention' : ''}`}>
            {/* FREE TIME PROGRESS BAR */}
            <div className="progress-section">
              <div className="progress-label">
                <span>Free Time</span>
                <span>{isInDetention ? 'EXCEEDED' : `${Math.ceil(freeTimeRemaining / 60)} min remaining`}</span>
              </div>
              <div className="progress-track">
                <div
                  className={`progress-fill ${freeTimePercent >= 100 ? 'exceeded' : freeTimePercent > 75 ? 'warning' : ''}`}
                  style={{ width: `${Math.min(freeTimePercent, 100)}%` }}
                />
              </div>
            </div>

            {/* MAIN TIME */}
            <div className="clock-display">
              <div className="clock-label">
                {isInDetention ? (
                  <span className="detention-label">
                    <AlertTriangle size={16} /> IN DETENTION
                  </span>
                ) : (
                  <span>Total Time on Site</span>
                )}
              </div>
              <div className={`clock-time ${isInDetention ? 'detention-time' : ''}`}>
                {formatTime(elapsed)}
              </div>
            </div>

            {/* DETENTION COUNTER */}
            {isInDetention && (
              <div className="detention-counter">
                <div className="detention-count-label">Detention Time</div>
                <div className="detention-count-value">{formatTime(detentionSeconds)}</div>
                <div className="detention-count-sub">{detentionMinutes} minutes billable</div>
              </div>
            )}

            {/* ARRIVAL TIME */}
            {arrivedAt && (
              <div className="arrival-info">
                <MapPin size={13} />
                Arrived {arrivedAt.toLocaleTimeString()}
                {departedAt && ` · Departed ${departedAt.toLocaleTimeString()}`}
              </div>
            )}

            {/* CONTROLS */}
            <div className="timer-controls">
              {!running && elapsed === 0 && (
                <button className="btn btn-primary btn-lg timer-btn" onClick={handleStart}>
                  <Play size={20} /> Start Timer
                </button>
              )}
              {running && (
                <button className="btn btn-danger btn-lg timer-btn" onClick={handleStop}>
                  <Square size={20} /> Stop Timer
                </button>
              )}
              {!running && elapsed > 0 && (
                <>
                  <button className="btn btn-secondary timer-btn" onClick={handleReset}>
                    Reset
                  </button>
                  {!saved && (
                    <button className="btn btn-primary timer-btn" onClick={handleSaveLog}>
                      Save Log
                    </button>
                  )}
                  {saved && (
                    <span className="saved-badge">
                      <CheckCircle size={16} /> Saved
                    </span>
                  )}
                  <button className="btn btn-secondary timer-btn" onClick={generateReport}>
                    <FileText size={16} /> Download Report
                  </button>
                </>
              )}
            </div>
          </div>

          {/* NOTES */}
          {(running || elapsed > 0) && (
            <div className="card">
              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Notes</label>
                <textarea
                  className="form-input"
                  placeholder="Document everything — who you spoke to, what was said, any issues..."
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                  rows={3}
                />
              </div>
            </div>
          )}
        </div>

        {/* PAST LOGS */}
        <div className="timer-sidebar">
          <div className="card">
            <h3 className="sidebar-title">Recent Logs</h3>
            {!user ? (
              <p className="sidebar-empty">Sign in to save and view your detention logs.</p>
            ) : pastLogs.length === 0 ? (
              <p className="sidebar-empty">No logs yet. Your detention history will appear here.</p>
            ) : (
              <div className="logs-list">
                {pastLogs.map(log => (
                  <div key={log.id} className="log-item">
                    <div className="log-facility">{log.facility_name}</div>
                    <div className="log-date">{new Date(log.arrived_at).toLocaleDateString()}</div>
                    <div className="log-stats">
                      <span className="stat-chip">
                        <Clock size={11} />
                        {formatDuration(Math.floor((new Date(log.departed_at) - new Date(log.arrived_at)) / 60000))} total
                      </span>
                      {log.detention_minutes > 0 ? (
                        <span className="badge badge-red">{formatDuration(log.detention_minutes)} detention</span>
                      ) : (
                        <span className="badge badge-green">No detention</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* INFO CARD */}
          <div className="card info-card">
            <h4><AlertTriangle size={16} /> Know Your Rights</h4>
            <ul>
              <li>Federal law requires detention pay after 2 hours free time (FMCSA)</li>
              <li>Standard rate is $25–75/hour depending on your contract</li>
              <li>Always document: facility name, arrival time, departure time</li>
              <li>A written detention request sent to the broker starts the clock officially</li>
              <li>Save every report — you may need it for a FMCSA complaint</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
